export class WalletModel {
    "id": 0;
    "hashId": "string";
    "name": "string";
    "referenceNo": 0;
    "referenceAlternate": "string";
    "contactId": 0;
    "contact": "string";
    "isInactive": true;
    "merchantCode": "string";
    "bankId": 0;
    "bic": "string";
    "business": 0;
    "trust": 0;
    "realTrust": 0;
    "realBusiness": 0;
    "realTradeLimit": 0;
    "tradeLimit": 0;
    "oneOffWithdrawalAmount": 0;
    "dailyWithdrawalLimit": 0;
    "realReserve": 0;
    "currencyCode": "string";
    "iban": "string";
    "symbol": "string";
    "newTransactionCount": 0;
    "merchant": "string";
    "isDefault": true;
    "lastTranHeadId": 0
  }